Lab 1
xm1ls/Hmilovskij_Lex_IPZ_32 pull request #1
Opened 2023-09-08 22:09 UTC by xm1ls

2023-09-08 22:21 UTC, xm1ls commented
review-ready lab-1

2023-09-09 08:42 UTC, vozniuk-lntu commented on index.html
> +      <h1>Ефективні рішення для вашого бізнесу</h1>
24 та 25 це окрема секція
hero клас потім можна навішати

2023-09-09 08:42 UTC, vozniuk-lntu commented on index.html
> +        <p>info@devstudio.com</p>
це link mailto

2023-09-09 08:42 UTC, vozniuk-lntu commented on index.html
> +        <p>+38 096 111 11 11</p>
link tel

2023-09-09 08:49 UTC, vozniuk-lntu commented on index.html
> +      <div>
переробити діви на секції, для цієї секції додати загоовок х2 в подальшому ми його сховаємо

2023-09-09 08:50 UTC, vozniuk-lntu commented on index.html
> +            <h3>УВАГА ДО ДЕТАЛЕЙ</h3>
тут не капс, капс робиться стилями

2023-09-09 08:51 UTC, vozniuk-lntu commented on index.html
> +        <p>info@devstudio.com</p>
тут теж посилання

2023-09-09 08:51 UTC, vozniuk-lntu requested changes
виправити коменти

2023-09-09 19:07 UTC, xm1ls commented on index.html
> +        <p>info@devstudio.com</p>
done

2023-09-09 19:10 UTC, xm1ls commented
мабуть не варто було ресолвати ваші коментарі, краще б вони висіли далі **Х\**

2023-09-11 18:46 UTC, vozniuk-lntu requested changes

2023-09-11 18:46 UTC, vozniuk-lntu commented on index.html
> +    <section>
не треба секція, це вже хедер

2023-09-11 18:46 UTC, vozniuk-lntu commented on index.html
> +      <h2>Header</h2>
прихований заголовок тут теж не треба, бо це не контектна секція а хедер

2023-09-11 18:46 UTC, vozniuk-lntu commented on index.html
> +          <li>Студія</li>
в лішках посилання

2023-09-11 18:46 UTC, vozniuk-lntu commented on index.html
> +      <a href="mailto:info@devstudio.com">info@devstudio.com</a>
ці дві ссилки в список

2023-09-11 18:46 UTC, vozniuk-lntu commented on index.html
> +    <section>
а в цю секцію вже можна прихований заголовок додати

2023-09-11 18:46 UTC, vozniuk-lntu commented on index.html
> +          <img src="./images/img-5.jpg" alt="we do great job" width="370" />
однакові alt, no no

2023-09-11 18:49 UTC, xm1ls commented on index.html
> +      <a href="mailto:info@devstudio.com">info@devstudio.com</a>
в докові до лаби написано що вони поза навом мають бути

2023-09-11 19:23 UTC, merged