lab-2
xm1ls/Hmilovskij_Lex_IPZ_32 pull request #2
Opened 2023-09-13 13:39 UTC by xm1ls

lab-2 pull request

2023-09-13 17:20 UTC, xm1ls commented
review-ready lab-2

2023-09-13 17:49 UTC, xm1ls commented
review-ready lab-2

2023-09-15 12:07 UTC, vozniuk-lntu requested changes
line-height
letter-spacing
ці властивості дописати

2023-09-15 12:07 UTC, vozniuk-lntu commented on portfolio.html
> +        <section class="filter-area">
однією секцією

2023-09-15 12:07 UTC, vozniuk-lntu commented on portfolio.html
> +                    <img src="images/portfolio/img-7.jpg" alt="Проєкт LAB" width="370" />
карточка є посиланням

2023-09-20 18:52 UTC, vozniuk-lntu approved these changes
синій колір це ховер https://i.imgur.com/fKLVEHy.png
не бачу транзішенів https://developer.mozilla.org/en-US/docs/Web/CSS/transition

це апрув, але оце виправити в третій лабі
https://docs.google.com/document/d/1Oeay7NWz9ltQyIij00fH-GLMeKd0Hec0/edit?usp=drive_link

2023-09-20 18:52 UTC, vozniuk-lntu commented on index.html
> +  <link rel="preconnect" href="https://fonts.googleapis.com">
ну як так
там два преконекта
тупо з сайту скопіювати ні?)

2023-09-20 18:52 UTC, vozniuk-lntu commented on index.html
> +<body class="body">
нема потреби в класі, можна просто на тег
він ж на сайті один
`+` по тегу якщо то гарантовоно переб'єш чимось іншим

2023-09-20 19:04 UTC, merged